name: Build ROM

on: [push]

jobs:
  build_rom:
    runs-on: ubuntu-latest
    name: Compile rom
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/cache_cc65
      - name: Build the game
        run: make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: famidash.nes
          path: BUILD/famidash.nes
